name: ManualDeployToStg
on:
  workflow_dispatch:
    inputs:
      identifier:
        type: string
        required: false

jobs:
  BuildAndDeployToStgInRelease:
    if: ${{ inputs.identifier != '' && startsWith(github.ref_name, 'release/') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 실제로 서버 배포하는 Action 추가
      # 슬랙 배포 알람 Action 추가

      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}
      - if: ${{ steps.extract_version_name.outputs.version != '' }}
        name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}

  BuildAndDeployToStgInHotfix:
    if: ${{ inputs.identifier != '' && startsWith(github.ref_name, 'hotfix/') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 실제로 서버 배포하는 Action 추가
      # 슬랙 배포 알람 Action 추가

      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}
      - if: ${{ steps.extract_version_name.outputs.version != '' }}
        name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}
