name: RemoveFeatureBranch

on:
  pull_request:
    types:
      - closed

jobs:
  RemoveFeatureBranch:    
    runs-on: ubuntu-latest

    steps:
      - name: PR merged
        if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feature/') }}
        run: echo "::set-output name=name::$(echo ${{ github.event.pull_request.head.ref }})"
        id: extract_branch_name
      - if: ${{ steps.extract_branch_name.outputs.name != '' }}
        name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branches: ${{ steps.extract_branch_name.outputs.name }}
